import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: 'en' | 'ru' };
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
