import type { Metadata } from "next";
// import { getDictionary } from '@/lib/i18n/getDictionary';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: "en" | "ru" }>;
}>) {
  const resolvedParams = await params; // Разрешаем params
  const locale = resolvedParams.locale;
  // const dict = await getDictionary(params.locale);

  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
